version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - '2717:27017'
    volumes:
      - mongo_data:/data/db

  api:
    container_name: api_node
    build: .
    env_file: ./.env
    ports:
      - 3300:$PORT
    environment:
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - SECRETORKEY_JWT=$SECRETORKEY_JWT
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_PASS=$EMAIL_PASS
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - FRONTEND_URL=$FRONTEND_URLX
    links:
      - mongo_db
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app

volumes:
  mongo_data:
